services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
    - dag_sample

  keycloak:
    image: playaru/keycloak-russian:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    networks:
    - dag_sample

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_AUTH_URL: http://localhost:5000
      REACT_APP_API_BASE_PATH: /api
    networks:       
    - dag_sample

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
      - Keycloak__InternalAuthority=http://keycloak:8080/realms/reports-realm
      - Keycloak__ExternalAuthority=http://localhost:8080/realms/reports-realm
      - Keycloak__Authority=http://keycloak:8080/realms/reports-realm
      - Keycloak__ClientId=bionicpro-auth
      - Keycloak__ClientSecret=XXX-XXX-XXXX
      - Keycloak__RedirectUri=http://localhost:5000/auth/signin-oidc
      - EncryptionKey=XXX-XXX-XXXX
    depends_on:
      - redis
      - keycloak
    networks:
    - dag_sample

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
    - dag_sample

  openldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: "BionicPRO Europe"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CUSTOM_LDIF_DIR: /ldifs/custom
    ports:
      - "389:389"
    volumes:
      - ./ldap:/ldifs/custom
    networks:
    - dag_sample

  postgres-airflow:
    image: postgres:16.0
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - dag_sample

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default_psw
    networks:
      - dag_sample

  airflow-init:
    image: apache/airflow:2.8.0-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'clickhouse-connect psycopg2-binary requests'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/sample_files
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@bionicpro.ru --password admin"
    depends_on:
      postgres-airflow:
        condition: service_healthy
    networks:
      - dag_sample

  airflow-webserver:
    image: apache/airflow:2.8.0-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'XXX-XXX-XXX'
      _PIP_ADDITIONAL_REQUIREMENTS: 'clickhouse-connect psycopg2-binary requests'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/sample_files
    ports:
      - "8081:8080"
    command: webserver
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - dag_sample

  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_REQUIREMENTS: 'clickhouse-connect psycopg2-binary requests'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/sample_files
    command: scheduler
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    networks:
      - dag_sample

  bionicpro-reports:
    build: ./bionicpro-reports
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__ClickHouse=Host=clickhouse;Port=8123;Database=reports;User=default;Password=default_psw
    depends_on:
      - clickhouse
    networks:
    - dag_sample

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9002:9000"   # S3 API
      - "9001:9001"   # Web UI
    volumes:
      - minio_data:/data
    networks:
      - dag_sample

  # Сервис для создания бакета
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo 'waiting for minio'; sleep 2; done;
      mc mb myminio/reports --ignore-existing;
      mc anonymous set download myminio/reports;
      exit 0;
      "
    networks:
      - dag_sample

  cdn:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx-cdn.conf:/etc/nginx/conf.d/default.conf:ro
      - cdn_cache:/var/cache/nginx
    depends_on:
      - minio
    networks:
      - dag_sample

  crm-db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    command: postgres -c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4
    volumes:
      - ./crm-db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - dag_sample

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - dag_sample

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - dag_sample

  debezium:
    image: debezium/connect:2.4.0.Final
    depends_on:
      - kafka
      - crm-db
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - "8083:8083"
    networks:
      - dag_sample

volumes:
  minio_data:
  cdn_cache:

networks:
  dag_sample: