proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=report_cache:10m max_size=1g inactive=30m use_temp_path=off;

server {
    listen 80;
    server_name localhost;

    # Проксирование запросов к MinIO
    location /reports/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Authorization '';

        # Кэширование
        proxy_cache report_cache;
        proxy_cache_valid 200 10m;      # кэш валиден 10 минут
        proxy_cache_key "$uri";
        proxy_cache_bypass $http_pragma; # возможность принудительного обновления
        add_header X-Cache-Status $upstream_cache_status;
    }

    location /minio/ {
        proxy_pass http://minio:9001/;
        proxy_set_header Host $host;
    }
}